Bump to semantic version 1.0.1
Ember don't like non-semantic versions...

```
> ember build
Invalid Version: 1.0
TypeError: Invalid Version: 1.0
```